# Generated by Django 3.0.4 on 2020-04-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name='邮件')),
                ('password', models.CharField(max_length=150, verbose_name='密码')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '注册用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
